#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./utils.sh
source "$SCRIPT_DIR/utils.sh"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --network <profile>    Network profile to use (mainnet, testnet)
  --moniker <name>       Validator moniker (overrides MONIKER env)
  --home <path>          Qubetics home directory (default $HOME_DIR)
  --workdir <path>       Working directory for upstream repos
  --env-file <path>      Load variables from a specific env file
  --help                 Show this help message
USAGE
}

HOME_DIR="${HOME_DIR:-/data/.qubeticsd}"
WORKDIR="${WORKDIR:-${HOME}/nodes/qubetics}"
MONIKER="${MONIKER:-Q-Sync}"
SERVICE_NAME="qubeticschain.service"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}"
REPO_URL="https://github.com/Qubetics/qubetics-mainnetnode-script"
REPO_BRANCH_MAINNET="main"
REPO_BRANCH_TESTNET="testnet"

if ! parse_common_args "$@"; then
  usage
  exit 0
fi

set -- "${COMMON_ARGS[@]}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --moniker)
      MONIKER="$2"; shift 2 ;;
    --home)
      HOME_DIR="$2"; shift 2 ;;
    --workdir)
      WORKDIR="$2"; shift 2 ;;
    --help)
      usage; exit 0 ;;
    --*)
      die "Unknown flag $1" ;;
    *)
      break ;;
  esac
done

say "Starting Qubetics bootstrap phase for network=$NETWORK_PROFILE"

if [[ $EUID -ne 0 ]]; then
  die "Bootstrap must be run as root"
fi

mkdir -p "$WORKDIR" "$HOME_DIR" "$REPORTS_DIR" /data

say "Updating apt repositories"
export DEBIAN_FRONTEND=noninteractive
if ! apt-get update -y >/dev/null 2>&1; then
  say "Warning: apt-get update failed; continuing with cached metadata"
fi

say "Installing required packages"
if ! apt-get install -y git curl jq ufw fail2ban build-essential unzip lz4 nginx certbot python3-certbot-nginx >/dev/null 2>&1; then
  say "Warning: package installation encountered issues"
fi

BRANCH="$REPO_BRANCH_MAINNET"
if [[ "$NETWORK_PROFILE" == "testnet" ]]; then
  BRANCH="$REPO_BRANCH_TESTNET"
fi

say "Cloning validator scripts from upstream (branch $BRANCH)"
REPO_DIR="$WORKDIR/qubetics-mainnetnode-script"
if [[ -d "$REPO_DIR/.git" ]]; then
  git -C "$REPO_DIR" fetch --all >/dev/null 2>&1 || true
  git -C "$REPO_DIR" checkout "$BRANCH" >/dev/null 2>&1 || true
  git -C "$REPO_DIR" reset --hard "origin/$BRANCH" >/dev/null 2>&1 || true
else
  mkdir -p "$WORKDIR"
  if git clone --branch "$BRANCH" "$REPO_URL" "$REPO_DIR" >/dev/null 2>&1; then
    say "Upstream repository cloned"
  else
    say "Warning: unable to clone upstream repository right now. Re-run bootstrap once network access is available."
  fi
fi

say "Running official install scripts (if present)"
if [[ -x "$REPO_DIR/fast-sync.sh" ]]; then
  bash "$REPO_DIR/fast-sync.sh" || die "Fast-sync script failed"
elif [[ -x "$REPO_DIR/ubuntu.sh" ]]; then
  bash "$REPO_DIR/ubuntu.sh" || die "Ubuntu install script failed"
else
  say "No bundled installer detected; assuming qubeticsd already installed"
fi

say "Writing systemd service unit"
cat <<SERVICE > "$SERVICE_FILE"
[Unit]
Description=Qubetics Validator Node (Q-Sync)
After=network-online.target
Wants=network-online.target

[Service]
User=root
Type=simple
Environment="LOG_LEVEL=${LOG_LEVEL}"
ExecStart=/usr/local/bin/qubeticsd start --home ${HOME_DIR} --moniker "${MONIKER}" --log_level ${LOG_LEVEL}
Restart=on-failure
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

say "Applying hardening profile"
bash "$SCRIPT_DIR/harden.sh"

CONFIG_FILE="${HOME_DIR%/}/config/config.toml"
mkdir -p "${HOME_DIR%/}/config"
RPC_LADDR="tcp://127.0.0.1:${RPC_PORT}"
P2P_LADDR="tcp://0.0.0.0:${P2P_PORT}"

if [[ ! -f "$CONFIG_FILE" ]]; then
  cat <<CFG > "$CONFIG_FILE"
# Generated by bootstrap.sh
[rpc]
laddr = "${RPC_LADDR}"
[p2p]
laddr = "${P2P_LADDR}"
persistent_peers = "${PEERS:-}"
CFG
else
  tmp_file="${CONFIG_FILE}.tmp"
  awk -v rpc="$RPC_LADDR" -v p2p="$P2P_LADDR" -v peers="${PEERS:-}" '
    BEGIN { in_rpc=0; in_p2p=0; rpc_set=0; p2p_set=0; peers_set=0 }
    /^\s*\[rpc\]\s*$/ { print; in_rpc=1; in_p2p=0; next }
    /^\s*\[p2p\]\s*$/ { print; in_p2p=1; in_rpc=0; next }
    in_rpc && /^\s*laddr\s*=\s*/ { if (!rpc_set) { print "laddr = \"" rpc "\""; rpc_set=1 } next }
    in_p2p && /^\s*laddr\s*=\s*/ { if (!p2p_set) { print "laddr = \"" p2p "\""; p2p_set=1 } next }
    in_p2p && /^\s*persistent_peers\s*=\s*/ { if (!peers_set) { print "persistent_peers = \"" peers "\""; peers_set=1 } next }
    { print }
    END {
      if (!rpc_set) {
        print "[rpc]";
        print "laddr = \"" rpc "\"";
      }
      if (!p2p_set || !peers_set) {
        print "[p2p]";
        if (!p2p_set) print "laddr = \"" p2p "\"";
        if (!peers_set) print "persistent_peers = \"" peers "\"";
      }
    }
  ' "$CONFIG_FILE" > "$tmp_file"
  mv "$tmp_file" "$CONFIG_FILE"
fi

say "Ensuring RPC loopback enforcement"
systemctl restart "$SERVICE_NAME"

say "Refreshing UFW rules"
ufw allow 22/tcp >/dev/null 2>&1 || true
ufw allow "${P2P_PORT}/tcp" >/dev/null 2>&1 || true
ufw deny "${RPC_PORT}/tcp" >/dev/null 2>&1 || true
ufw --force enable >/dev/null 2>&1 || true

say "Waiting for node RPC to become available"
ATTEMPTS=0
until curl -fsS "http://127.0.0.1:${RPC_PORT}/status" >/dev/null 2>&1; do
  sleep 5
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 60 )); then
    die "RPC endpoint did not become ready in time"
  fi
  say "... still waiting for RPC (attempt $ATTEMPTS)"
done

NODE_ID="$(qubeticsd tendermint show-node-id --home "$HOME_DIR" 2>/dev/null || echo 'unknown')"
STATUS_JSON="$(curl -fsS "http://127.0.0.1:${RPC_PORT}/status" 2>/dev/null || echo '{}')"
SYNC_INFO="$(printf '%s' "$STATUS_JSON" | json '.result.sync_info.catching_up' 2>/dev/null || echo 'unknown')"
LADDR="$(toml_get_laddr || echo 'unknown')"
UFW_STATUS="$(ufw status || true)"

REPORT_FILE="${REPORTS_DIR}/bootstrap.md"
cat <<MARKDOWN > "$REPORT_FILE"
# Bootstrap Report

- Timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
- Network: $NETWORK_PROFILE ($CHAIN_ID)
- Moniker: $MONIKER
- Node ID: $NODE_ID
- RPC laddr: $LADDR
- catching_up: $SYNC_INFO
- Log level: $LOG_LEVEL

## UFW Rules

```
$UFW_STATUS
```

Next steps:
1. Securely import your validator key (mnemonic must never touch this server).
2. Run: `qubeticsd keys add validator --recover --keyring-backend file --home "$HOME_DIR"`
3. Continue with: `make finish`
MARKDOWN

say "Bootstrap completed. Validator service is running."
say "Report written to $REPORT_FILE"
