#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./utils.sh
source "$SCRIPT_DIR/utils.sh"

WORKDIR="${WORKDIR:-${HOME}/nodes/qubetics}"
MONIKER_INPUT="${1:-${MONIKER:-Q-Sync}}"
MONIKER="${MONIKER_INPUT:-Q-Sync}"
REPO_URL="https://github.com/Qubetics/qubetics-mainnetnode-script"
REPO_DIR="$WORKDIR/qubetics-mainnetnode-script"
SERVICE_NAME="qubeticschain.service"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}"
HOME_DIR="${HOME_DIR:-/data/.qubeticsd}"
REPORT_FILE="${REPORTS_DIR}/bootstrap.md"

say "Starting Qubetics bootstrap phase"

if [[ $EUID -ne 0 ]]; then
  die "Bootstrap must be run as root"
fi

mkdir -p "$WORKDIR" "$HOME_DIR" "$REPORTS_DIR" /data

say "Updating apt repositories"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y >/dev/null

say "Installing required packages"
apt-get install -y git curl jq ufw fail2ban build-essential unzip lz4 nginx certbot python3-certbot-nginx >/dev/null

say "Cloning validator scripts from upstream"
if [[ -d "$REPO_DIR/.git" ]]; then
  git -C "$REPO_DIR" fetch --all >/dev/null 2>&1 || true
  git -C "$REPO_DIR" reset --hard origin/main >/dev/null 2>&1 || true
else
  mkdir -p "$WORKDIR"
  if git clone "$REPO_URL" "$REPO_DIR" >/dev/null 2>&1; then
    say "Upstream repository cloned"
  else
    say "Warning: unable to clone upstream repository right now. Re-run bootstrap once network access is available."
  fi
fi

say "Running official install scripts (if present)"
if [[ -x "$REPO_DIR/fast-sync.sh" ]]; then
  bash "$REPO_DIR/fast-sync.sh" || die "Fast-sync script failed"
elif [[ -x "$REPO_DIR/ubuntu.sh" ]]; then
  bash "$REPO_DIR/ubuntu.sh" || die "Ubuntu install script failed"
else
  say "No bundled installer detected; assuming qubeticsd already installed"
fi

say "Writing systemd service unit"
cat <<SERVICE > "$SERVICE_FILE"
[Unit]
Description=Qubetics Validator Node (Q-Sync)
After=network-online.target
Wants=network-online.target

[Service]
User=root
Type=simple
ExecStart=/usr/local/bin/qubeticsd start --home $HOME_DIR --moniker "$MONIKER"
Restart=on-failure
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

say "Applying hardening profile"
bash "$SCRIPT_DIR/harden.sh"

CONFIG_FILE="${HOME_DIR%/}/config/config.toml"
mkdir -p "${HOME_DIR%/}/config"
if [[ ! -f "$CONFIG_FILE" ]]; then
  cat <<'CFG' > "$CONFIG_FILE"
# Generated by bootstrap.sh
[rpc]
laddr = "tcp://127.0.0.1:26657"
CFG
else
  tmp_file="${CONFIG_FILE}.tmp"
  awk '
    BEGIN { in_rpc=0; set=0 }
    /^\s*\[rpc\]\s*$/ { print; in_rpc=1; next }
    in_rpc && /^\s*\[/ {
      if (!set) {
        print "laddr = \"tcp://127.0.0.1:26657\""
        set=1
      }
      in_rpc=0
    }
    {
      if (in_rpc && /^\s*laddr\s*=/) {
        if (!set) {
          print "laddr = \"tcp://127.0.0.1:26657\""
          set=1
        }
        next
      }
      print
    }
    END {
      if (in_rpc && !set) {
        print "laddr = \"tcp://127.0.0.1:26657\""
        set=1
      }
      if (!set) {
        if (!in_rpc) {
          print ""
          print "[rpc]"
        }
        print "laddr = \"tcp://127.0.0.1:26657\""
      }
    }
  ' "$CONFIG_FILE" > "$tmp_file"
  mv "$tmp_file" "$CONFIG_FILE"
fi

say "Ensuring RPC loopback enforcement"
systemctl restart "$SERVICE_NAME"

say "Refreshing UFW rules"
ufw allow 22/tcp >/dev/null 2>&1 || true
ufw allow 26656/tcp >/dev/null 2>&1 || true
ufw deny 26657/tcp >/dev/null 2>&1 || true
ufw --force enable >/dev/null 2>&1 || true

say "Waiting for node RPC to become available"
ATTEMPTS=0
until curl -sf http://127.0.0.1:26657/status >/dev/null; do
  sleep 5
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 60 )); then
    die "RPC endpoint did not become ready in time"
  fi
  say "... still waiting for RPC (attempt $ATTEMPTS)"
done

NODE_ID="$(qubeticsd tendermint show-node-id --home "$HOME_DIR" 2>/dev/null || echo 'unknown')"
STATUS_JSON="$(curl -s http://127.0.0.1:26657/status || echo '{}')"
SYNC_INFO="$(printf '%s' "$STATUS_JSON" | json '.result.sync_info.catching_up' 2>/dev/null || echo 'unknown')"
LADDR="$(toml_get_laddr || echo 'unknown')"
UFW_STATUS="$(ufw status || true)"

cat <<MARKDOWN > "$REPORT_FILE"
# Bootstrap Report

- Timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
- Moniker: $MONIKER
- Node ID: $NODE_ID
- RPC laddr: $LADDR
- catching_up: $SYNC_INFO

## UFW Rules

```
$UFW_STATUS
```

Next steps:
1. Securely import your validator key (mnemonic must never touch this server).
2. Run: `qubeticsd keys add validator --recover --keyring-backend file --home "$HOME_DIR"`
3. Continue with: `make finish`
MARKDOWN

say "Bootstrap completed. Validator service is running."
say "Report written to $REPORT_FILE"
